version: "3.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "SAVE_ORDER_TOPIC:4:1"
    ports:
      - 9092:9092
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: ambevtech
    ports:
      - 27017:27017
